### PR TITLE
enable route creation

### PR DESCRIPTION
**Pull request by chrira**
Add OCP route template to be created.
Enable ingress for K8S and route for OCP.

### CODE REVIEW

**Comment by splattner** [comment]
Why? Ingress do work on OpenShift

**Comment by bliemli** [comment]
@chrira Also see the additon @millhaus just made, with `emptyTLS` it'll work.

**Comment by bliemli** [comment]
Here's an example: https://github.com/puzzle/ansible-training/pull/189

**Comment by chrira** [comment]
Problem solved with emptyTLS, thanks.

**Pull request closed without merging**
